### ISSUE TITLE
Error when running code

### ISSUE THREAD

**Issue by 10Kpapers** [amurtadha/BERT-ASC#2]
Hi @amurtadha ,

I'm trying to train BERT-ASC, when I running 
`
python run.py --dataset semeval --device cuda:0
`

_Traceback (most recent call last):
  File "run.py", line 14, in <module>
    from layers.optimization  import BertAdam
ModuleNotFoundError: No module named 'layers.optimization'_

I also found that code/plm/pt/ is empty.

Could you please update layers and plm/pt ?

Many Thanks:)

**Comment by amurtadha** [comment]
I have updated the code. Please lemme know if there is any other issue. Thanks
